# Generated by Django 3.2.19 on 2023-09-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20230923_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseitem',
            name='completed',
        ),
    ]
