# Generated by Django 3.2.19 on 2023-09-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_instanceitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstanceItem',
        ),
    ]
