# Generated by Django 3.2.19 on 2023-09-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_delete_instanceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(default=0)),
                ('sem', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
