# Generated by Django 3.2.19 on 2023-09-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_sem_instanceitem_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('year', models.CharField(max_length=4)),
                ('semester', models.CharField(max_length=10)),
            ],
        ),
    ]
