# Generated by Django 3.2.19 on 2023-09-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_createcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateCourse',
        ),
    ]
