# Generated by Django 3.2.19 on 2023-09-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_delete_createcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceitem',
            name='course_id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
