# Generated by Django 3.2.19 on 2023-09-25 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_instanceitem_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instanceitem',
            name='course_id',
        ),
    ]
